version: "2"

volumes: 
  db-data: 
    external: false

services: 
  db: 
    image: postgres
    env_file: .env_postgres
    volumes: 
      - db-data:/var/lib/postgresql/db-data

  app: 
    build: .
    env_file: .env_postgres
    volumes: 
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on: 
      - db